---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: permissions-sa
  labels:
    app.kubernetes.io/component: permissions
    app.kubernetes.io/name: banking-demo

---
apiVersion: v1
kind: Service
metadata:
  name: permissions
  labels:
    app.kubernetes.io/component: permissions
    app.kubernetes.io/name: banking-demo
spec:
  selector:
    app.kubernetes.io/component: permissions
    app.kubernetes.io/name: banking-demo
  ports:
    - name: http
      port: 80
      targetPort: 8081
  type: ClusterIP

---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: permissions-vs
  labels:
    app.kubernetes.io/component: permissions
    app.kubernetes.io/name: banking-demo
spec:
  hosts:
    - "*"
  gateways:
    - banking-demo-gw
  http:
    - match:
        - uri:
            prefix: /permissions
      route:
        - destination:
            port:
              number: 80
            host: permissions

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: permissions-deploy
  labels:
    app.kubernetes.io/component: permissions
    app.kubernetes.io/name: banking-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: permissions
      app.kubernetes.io/name: banking-demo
  template:
    metadata:
      labels:
        opa-istio-authz: "false"
        app.kubernetes.io/component: permissions
        app.kubernetes.io/name: banking-demo
    spec:
      serviceAccountName: permissions-sa
      containers:
        - name: permissions
          image: adamsandor83/permissions:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          livenessProbe:
            httpGet:
              path: /status
              scheme: HTTP
              port: 8081
            initialDelaySeconds: 45
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /status
              scheme: HTTP
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 256Mi

