---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: status-sa
  labels:
    app.kubernetes.io/component: status
    app.kubernetes.io/name: banking-demo

---
apiVersion: v1
kind: Service
metadata:
  name: status
  labels:
    app.kubernetes.io/component: status
    app.kubernetes.io/name: banking-demo
spec:
  selector:
    app.kubernetes.io/component: status
    app.kubernetes.io/name: banking-demo
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP

---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: status-vs
  labels:
    app.kubernetes.io/component: status
    app.kubernetes.io/name: banking-demo
spec:
  hosts:
    - "*"
  gateways:
    - banking-demo-gw
  http:
    - match:
        - uri:
            prefix: /status
      route:
        - destination:
            port:
              number: 80
            host: status

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: status-deploy
  labels:
    app.kubernetes.io/component: status
    app.kubernetes.io/name: banking-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: status
      app.kubernetes.io/name: banking-demo
  template:
    metadata:
      labels:
        opa-istio-authz: "true"
        app.kubernetes.io/component: status
        app.kubernetes.io/name: banking-demo
    spec:
      serviceAccountName: status-sa
      containers:
        - name: status
          image: adamsandor83/status:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /status
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /status
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5

