apiVersion: apps/v1
kind: Deployment
metadata:
  name: ignored
spec:
  template:
    spec:
      containers:
        - name: opa
          image: openpolicyagent/opa:latest-istio
          imagePullPolicy: Never
          args:
            - "run"
            - "--server"
            - "--ignore=.*"
            - "--config-file=/config/opa-conf.yaml"
            - "--log-level=error"
            - "--addr=http://localhost:8181"
            - "--diagnostic-addr=0.0.0.0:8282"
          env:
            - name: GCS_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: gcs-credentials
                  key: pk
          volumeMounts:
            - readOnly: true
              mountPath: /config
              name: opa-config-vol
          livenessProbe:
            httpGet:
              path: /health
              scheme: HTTP
              port: 8282
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health?bundle=true
              scheme: HTTP
              port: 8282
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: opa-config-vol
          configMap:
            name: opa-config